### PR TITLE
Fix data race crash (and other minor code quality improvements)

### PR DESCRIPTION
**Pull request by emidoots**
Fixes azul3d/engine#150 among other things.

### CODE REVIEW

**Comment by nwidger** [comment]
Thanks for looking into this!  I just quickly tried out the PR and it looks like it might need a bit more work.  On my Mac, hitting P to pause or Q to quit nintengo locks it up and I have to ^C from the terminal.  Does that happen to you as well?

**Comment by slimsag** [comment]
Hmm, you're right, that does happen for me too. It must be because of the change to making input tied to the `gfxLoop`. I'll look into it

**Comment by nwidger** [comment]
I took a look at this and I think I've reconfigured the shutdown process to be simpler and hopefully more correct.  Just plop this into your branch and let me know if it works for you:

https://gist.github.com/nwidger/22dee7994fd5a46fbc2b

**Comment by slimsag** [comment]
@nwidger that definitely fixes the issue for me, and looks like a good change as well! I applies it on top of my branch (commit `23fbeb5`). I also made a follow-up change to cause event processing to occur in a separate goroutine. This fixes the issue with P causing nintengo to lock-up forever.

**Comment by nwidger** [comment]
Looks good to me, I'll merge this back to `master`.  As usual, thanks for the help! :)

**Pull request merged**
