### PR TITLE
Demo: Networking feature

### PR DESCRIPTION
**Pull request by kaicheng**
Hi all,

I have added the networking feature to this emulator, i.e. play with your friend over the internet!

This pull request is just an early demo. It still needs some work to improve performance and more tests. I put it here just want to get comments as early as possible.

The general idea is reworking on the event processing framework. Nintengo's original event framework is pretty good. I just did a little modification to let those events being able to transmit via TCP connections. All the events now have a flag. Check nes/events.go:GetEventFlag(). Basically, the events that need synchronization will go through TCP connections. Others can be processed locally async.

One thing to mention that the processing of  those events need sync has moved to the loop of CPU, PPU etc.

The NES struct maintains a Tick. The master maintain the state, and run as usual. The slave is driven by events sent from master (control, heartbeats, etc..)

To test it, simply run
./nintengo -l ":8080" rom-file
as master.
./nintengo -c ":8080"
as slave. Slave doesn't need a rom-file to bootup.
The keys for master and slave are the same, but key strokes in slave will be 2nd player's.

I just tested it with my friend in my home wifi.

I would love to hear your thoughts! Hope you have fun.

Best,
Kaicheng

### CODE REVIEW

**Comment by nwidger** [comment]
This looks really cool! I'll take a closer look at it soon.  :-)

**Comment by nwidger** [comment]
@kaicheng so I've given your PR a look and really like where you're going with this awesome feature.  I wrote down a few comments as I was looking at your commits:

- Definitely `gofmt` any files you change, I've noticed some extra whitespace and the like that `gofmt` removes
- I would prefer `-listen`/`-connect` instead of `-l`/`-c` for the CLI args to stay consistent with the existing ones.
- Simple games like Super Mario Bros work great, but with Zelda the slave dies with a `Failed to sync with master` error on pressing Start on the title screen.  Not sure what's going on there, we'll have to investigate further...
- I think it would be cleaner to add a `Flag() uint` method to the `Event` interface rather than using the `GetEventFlag` method that you added.
- I would prefer any constants use camel case, so `EvGlobal` instead of `EV_GLOBAL`
- Do we want some kind of compatibility check at the start to ensure that the master/slave are running the same "version" (whatever that means) of nintengo?
- I'm not positive that the `ForceAddMappings` calls are necessary.  If the master and slave both initialize an `NES` instance using the same ROM byte slice, all the mappings and such should be the same.
- Obviously before we merge this we need to remove the debug printouts that are in there

If you want to get together and chat about this I can send you my email.  I also hang around on #go-nuts on Freenode and the Gophers team on Slack.  Either way, it'd probably help us hash things out.

And again, thank you so much for what you've already done.  This is a really cool feature and I definitely want to get it into `master` soon. :)

Niels

**Comment by kaicheng** [comment]
@nwidger Glad to hear from you!

I've put my responses regarding your comments below. Actually, I tested the
implementation on a laggy networks using "Apple Network Link Conditioner",
and the current implementation is playable, but don't have a good
experience. I am thinking to implement some techniques, such as client side
prediction, to hide these latencies. I am going to make a new PR according
to you comments, then make a another one regarding the improvements. How
does it sound to you?


On Thu, Jan 29, 2015 at 5:55 PM, Niels Widger <notifications@github.com>
wrote:

> @kaicheng <https://github.com/kaicheng> so I've given your PR a look and
> really like where you're going with this awesome feature. I wrote down a
> few comments as I was looking at your commits:
>
>    - Definitely gofmt any files you change, I've noticed some extra
>    whitespace and the like that gofmt removes
>
> Sure

>
>    - I would prefer -listen/-connect instead of -l/-c for the CLI args to
>    stay consistent with the existing ones.
>
> Sure

>
>    - Simple games like Super Mario Bros work great, but with Zelda the
>    slave dies with a Failed to sync with master error on pressing Start
>    on the title screen. Not sure what's going on there, we'll have to
>    investigate further...
>
> Could I have the exact version of the ROM you tested, and how you
triggered the error? I will try to trigger this bug and investigate it.

>
>    - I think it would be cleaner to add a Flag() uint method to the Event
>    interface rather than using the GetEventFlag method that you added.
>
> Certainly. I was thinking this design too. I chose the GetEventFlag
version just because I can put all the flag code in one place.

>
>    - I would prefer any constants use camel case, so EvGlobal instead of
>    EV_GLOBAL
>
> Sure

>
>    -
>    - Do we want some kind of compatibility check at the start to ensure
>    that the master/slave are running the same "version" (whatever that means)
>    of nintengo?
>
> Yes, it would be better. We can use the meta.json in Save/Load state
serialization.

>
>    - I'm not positive that the ForceAddMappings calls are necessary. If
>    the master and slave both initialize an NES instance using the same
>    ROM byte slice, all the mappings and such should be the same.
>
> The current implementation do not require the slave has the ROM file. The
rom is provided by the master just after the connection is setup. So during
initialization time, the slave only has an empty ROM, and I do a remapping
when it received the ROM. You are right, the ForceAddMappings is not
necessary, we can just postpone AddMappings of slave's ROM space until
slave got the ROM data.

>
>    - Obviously before we merge this we need to remove the debug printouts
>    that are in there
>
> If you want to get together and chat about this I can send you my email. I
> also hang around on #go-nuts on Freenode and the Gophers team on Slack.
> Either way, it'd probably help us hash things out.
>
Sounds good. Either way works for me, and I should be available for
chatting this weekend.

>
>
And again, thank you so much for what you've already done. This is a really
> cool feature and I definitely want to get it into master soon. :)
>
No problem! The nintengo project is very well designed, and working on it
is so much fun!

> Niels
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwidger/nintengo/pull/16#issuecomment-72128978>.
>



-- 
Kaicheng Zhang

**Comment by nwidger** [comment]
> I've put my responses regarding your comments below. Actually, I tested the implementation on a laggy networks using "Apple Network Link Conditioner", and the current implementation is playable, but don't have a good experience. I am thinking to implement some techniques, such as client side prediction, to hide these latencies. I am going to make a new PR according to you comments, then make a another one regarding the improvements. How does it sound to you?

Yes, I'd say let's use this PR to get the basic feature in more or less as-is and then try improving its performance later.

> Yes, it would be better. We can use the meta.json in Save/Load state serialization.

I was planning to bump the version in `meta.json` only when there was a compatibility change as far as the JSON serialization goes.  This netplay feature would also need to ensure that the `Event` structs are compatible between server/client as well.

> Could I have the exact version of the ROM you tested, and how you triggered the error? I will try to trigger this bug and investigate it.

If you're familiar with GoodSet's notation, I'm seeing the crash using `Legend of Zelda, The (U) (PRG0) [!].nes`.  Just load it up and press Start at the title screen to make the slave die.

> The current implementation do not require the slave has the ROM file. The rom is provided by the master just after the connection is setup. So during initialization time, the slave only has an empty ROM, and I do a remapping when it received the ROM. You are right, the ForceAddMappings is not necessary, we can just postpone AddMappings of slave's ROM space until slave got the ROM data.

Perhaps it would be easier if we remove the `filename` parameter from `NewNES` and have a new `NES.LoadROM` method or something similar.  That way the slave can initialize its `NES` instance, connect to the master, download the ROM and call `LoadROM` on it.  The master can just call `LoadROM` immediately, obviously.  I think something along those lines would be cleaner than copying the `AddMappings` calls into `LoadStateFromReader`.  What do you think?

**Comment by nwidger** [comment]
Also, I just noticed that the call to `fmt.Println(nes.ROM)` at the top of `NES.Run` is printing `<nil>` on the client since it runs before the client has received the ROM.  I think this another indicator that there should be something between `NewNES` and `NES.Run` in `main()` which loads the ROM file as appropriate for the master/slave.

**Comment by kaicheng** [comment]
OK, I've fixed the issue with Zelda (commit b95eaf1). The problem is the previous implementation cannot restore RAM data in the ROMFile. The current use the following step:
1. Use ROM file bytes (ROMFileRaw.Raw) to create a ROM structure, including ROMFile.
2. Use other data (ROMFileRaw.*Banks) to restore all data in ROMFile.
It has the overhead in terms of data transmission, as the raw bytes are not necessary. But here, we need it to figure out which type of the ROM struct it is and other meta data.
Another (maybe cleaner) way is to export all fields in all the ROM structs and RomFile structs, and just use gob package. However this involves too much refactoring at the moment.
Yes, we need to rethink how we can load/restore/transmit ROMs with good interfaces..

**Comment by nwidger** [comment]
I would be in favor or just gob'ing the `ROM` instance.  I'm going to jump in here and see if I can refactor ROM/ROMFile so that that is possible.  And actually, I think you may have hit upon the reason why normal save/load state sometimes did not work.  Games write data to the vrom/wram banks in ROMFile, but I was not storing those in the save state file anywhere, so the emulator was not being restored to the exact state on load.  Whoops!  So at least those two fields in ROMFile should definitely be exported and stored in the save state JSON.

**Comment by nwidger** [comment]
@kaicheng I just committed to `master` changes that should make it possible to just gob encode the whole `ROM` instance and send it over to the slave.  Let me know what you think.

**Comment by kaicheng** [comment]
Sounds good! Now the problem is how to get these commits organized as the two branches have conflicts now. I am not familiar github's way of doing branch synchronization.. Let's try to commit this PR before we move on further on refactoring state restoring:
1. I will make this PR consistent to the up-to-date master branch. Which command should I use, rebase or merge?
2. We can work together so that this PR meets the quality requirement to merge.
3. Then we start working on how to improve the implementation of the state saving and loading.
What's your thoughts?

**Comment by nwidger** [comment]
@kaicheng Okay I just merged your branch into master and committed it.  At this point, I think we should definitely clean up the ROM loading on the slave.  I'd like to simply be able to gob encode the `ROM` instance and send it over and be done with it.  If that works we should be able to eliminate the `raw` field from `ROMFile` and some of the other methods that were added.  I'll also see if we can make it easier to break apart the initialization of the `NES` instance with the loading of the ROM.

Again, it'd probably be convenient if we could chat about this somewhere.  I created a #nintengo channel on the Gophers Slack team in case you want to hop on there.

**Comment by kaicheng** [comment]
Sounds good! How about today? I am free today, just pick a time that works best for you. I will go to the channel :)

**Comment by kaicheng** [comment]
err, I am not in the slack team. How about IRC?

**Comment by shurcooL** [comment]
> err, I am not in the slack team.

That's easy to change, if you want to. Just fill out [this form](http://bit.ly/go-slack-signup) and you'll be automatically sent an invite. I highly recommend Slack!

**Comment by kaicheng** [comment]
I see. Thanks for the instruction!

On Sun, Feb 1, 2015 at 11:22 AM, Dmitri Shuralyov <notifications@github.com>
wrote:

> err, I am not in the slack team.
>
> That's easy to change, if you want to. Just fill out this form
> <http://bit.ly/go-slack-signup> and you'll be automatically sent an
> invite. I highly recommend Slack!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwidger/nintengo/pull/16#issuecomment-72373766>.
>



-- 
Kaicheng Zhang (Chinese Name: 张凯程)

**Comment by nwidger** [comment]
@kaicheng FYI I'm on Slack now

**Pull request merged**
